### ISSUE TITLE
Getting an AttributeError

### ISSUE THREAD

**Issue by robins80** [judell/Hypothesis#4]
I'm trying to use your library and I get this error:

`AttributeError: module 'hypothesis' has no attribute 'Hypothesis'`

The code is:
```
import hypothesis

hypothesis_key = '6879-RnNppXabSn096aLrJ9erFmYdu7euhIR7tPOo4misB_w'
hypothesis_url = 'https://api.hypothes.is/api/search'

hclient = hypothesis.Hypothesis(
            domain = "hypothes.is",
            authority = "hypothes.is",
            username = 'robins80',
            token = hypothesis_key,
            debug = True,
        )
```
I'm using python 3.7.4, so I don't understand why this is happening.

**Comment by judell** [comment]
The last change I made here was to (finally) make this thing installable from PyPI, as `hypothesis-api`.  Which I realize isn't mentioned here anywhere, sorry!

```
$ pip3 install hypothesis-api
Collecting hypothesis-api
  Downloading hypothesis_api-1.0.1-py3-none-any.whl (9.0 kB)
Installing collected packages: hypothesis-api
Successfully installed hypothesis-api-1.0.1
$ python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15)
>>> from hypothesis import Hypothesis
>>> Hypothesis.search
<function Hypothesis.search at 0x7f723398ed30>
>>> hclient = Hypothesis(
...   domain = "hypothes.is",
...   authority = "hypothes.is",
...   username = 'robins80'
... )
>>>
>>> hclient.search( {'user':'judell', 'limit':1} )
{'total': 5753, 'rows': [{'id': '_0wHAn7pEeuuxRPdNUrE6w', 'created': '2021-03-07T02:08:23.949206+00:00', 'updated':  ...
```

**Comment by robins80** [comment]
I had done that, but still got the error.
    On Wednesday, March 17, 2021, 02:34:36 PM EDT, Jon Udell ***@***.***> wrote:  
 
 


The last change I made here was to (finally) make this thing installable from PyPI, as hypothesis-api. Which I realize isn't mentioned here anywhere, sorry!
$ pip3 install hypothesis-api
Collecting hypothesis-api
  Downloading hypothesis_api-1.0.1-py3-none-any.whl (9.0 kB)
Installing collected packages: hypothesis-api
Successfully installed hypothesis-api-1.0.1
$ python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15)
>>> from hypothesis import Hypothesis
>>> Hypothesis.search
<function Hypothesis.search at 0x7f723398ed30>
>>> hclient = Hypothesis(
...   domain = "hypothes.is",
...   authority = "hypothes.is",
...   username = 'robins80'
... )
>>>
>>> hclient.search( {'user':'judell', 'limit':1} )
{'total': 5753, 'rows': [{'id': '_0wHAn7pEeuuxRPdNUrE6w', 'created': '2021-03-07T02:08:23.949206+00:00', 'updated':  ...

**Comment by robins80** [comment]
I changed my code to:
```
from hypothesis import Hypothesis

hypothesis_key = '6879-RnNppXabSn096aLrJ9erFmYdu7euhIR7tPOo4misB_w'
hypothesis_url = 'https://api.hypothes.is/api/search'

hclient = Hypothesis(
            domain = "hypothes.is",
            authority = "hypothes.is",
            username = 'robins80',
            token = hypothesis_key,
            debug = True,
        )
```
And the error I get now is:
`ImportError: cannot import name 'Hypothesis' from 'hypothesis'`

**Comment by robins80** [comment]
If I try it from the python command line, everything is fine.  When I try to run the python code, I get the error.  The problem must be on my end somehow.  Thanks for responding so quickly.
